version: 2.0

jobs:
  Nexus:
    docker:
      - image: ubuntu:jammy-20211029
    steps:
      - run: apt update && apt upgrade -y
      - run: ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && date
      - run: apt install -f -y git bison flex libxml2 libssl-dev bc zip default-jre python3 python3-pip wget curl cpio lld ccache
      - run: git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} .
      - run: wget https://raw.githubusercontent.com/arnavpuranik/myscripts/main/kernel_build.sh
      - run: bash kernel_build.sh clean
workflows:
  version: 2
  build:
    jobs:
      - Nexus
